"""LLM endpoint resolution for xAI/Grok calls.

Single source of truth for where xAI requests get sent. Two paths:

  1. LLM proxy (preferred). When LLM_PROXY_BASE_URL and
     LLM_PROXY_API_KEY are set, every xAI call routes through a
     local proxy. The master XAI_API_KEY lives only inside the
     proxy process; frame-check never sees it.

  2. Direct xAI fallback. When the proxy env is unset but
     XAI_API_KEY is set, falls back to api.x.ai/v1 directly. Used
     by deploys that do not run a proxy in front.

Resolution order: proxy > direct > unconfigured. The OR-fallback
shape means a misconfigured proxy (e.g., LLM_PROXY_BASE_URL set but
LLM_PROXY_API_KEY missing) cleanly degrades to direct rather than
silently breaking analysis.

This module is imported wherever frame-check builds an OpenAI-SDK
client for xAI, plus the V4.2 engine which uses urllib directly.

Provider-display constant: LLM_PROVIDER_DISPLAY surfaces in user-
facing chips ("AI narrative * generated by {LLM_PROVIDER_DISPLAY}").
Centralized here so a future provider swap touches one line, not a
search-and-replace across templates and tests. Distinct from the
model identifier (the actual API call target): the proxy may route
to a different downstream model than the display name claims.
"""

import os
from typing import Any, Optional, Tuple


LLM_PROVIDER_DISPLAY = "Grok"


def xai_endpoint() -> Tuple[Optional[str], Optional[str]]:
    """Return (base_url, api_key) for xAI calls, or (None, None).

    Proxy first, direct second. (None, None) when neither path is
    configured, which signals "do not call xAI" to every caller and
    keeps Layer A as the sole framing analysis.
    """
    proxy_url = os.environ.get("LLM_PROXY_BASE_URL", "").strip()
    proxy_key = os.environ.get("LLM_PROXY_API_KEY", "").strip()
    if proxy_url and proxy_key:
        return proxy_url.rstrip("/"), proxy_key
    direct_key = os.environ.get("XAI_API_KEY", "").strip()
    if direct_key:
        return "https://api.x.ai/v1", direct_key
    return None, None


def xai_configured() -> bool:
    """True iff some xAI call path (proxy or direct) is reachable.

    Replaces the bare ``os.environ.get("XAI_API_KEY")`` checks scattered
    across app.py and the engine modules so that proxy-only deploys
    do not see V4.2 disabled despite having a valid path.
    """
    base, key = xai_endpoint()
    return bool(base and key)


def xai_openai_client() -> Any:
    """Build an OpenAI-SDK client for xAI calls.

    Returns None when no xAI path is configured. Callers must branch on
    the None return; constructing an OpenAI client with empty base_url
    or api_key would silently 401 on first request rather than fall
    cleanly into Layer A.

    Return type is Any because openai.OpenAI is an optional runtime
    dependency: pip-installed wheels carry it, but mypy --strict on the
    seven-module wheel surface does not import it. Annotating Any here
    keeps callers in the strict surface from needing a per-call cast.
    """
    base, key = xai_endpoint()
    if not (base and key):
        return None
    from openai import OpenAI
    return OpenAI(api_key=key, base_url=base)


# Standard punctuation-style instruction appended to every Grok user
# prompt that produces reader-facing text. Grok's default register
# uses em-dashes and curly quotes, which violate the project WRITING
# RULES (no em/en-dashes anywhere user-facing). Stated as a hard
# constraint because softer phrasing ("avoid where possible") gets
# treated as advisory and Grok keeps emitting em-dashes in roughly
# half of completions.
#
# The literal em/en-dash and ellipsis characters are written as
# Unicode escapes so the source file does not itself trigger the
# project's em-dash pre-commit hook (scripts/check_no_em_dashes.py).
# At runtime Python decodes them; the prompt sent to Grok contains
# the actual characters, which is what the model needs to see in
# order to refuse to emit them.
PUNCTUATION_RULE = (
    "Use only straight ASCII punctuation. Do not use em-dashes "
    "(\u2014), en-dashes (\u2013), curly quotes, curly apostrophes, "
    "or ellipsis characters (\u2026). If you would use an em-dash, "
    "rewrite the sentence with a comma, colon, period, or "
    "parenthesis instead."
)
