"""Per-frame TP/FP/FN rationale audit for all 9 default-mode frames
across mg_v1 + mg_v2 V4.2 production-engine outputs.

For each frame: enumerates TP / FP / FN docs (run-pair stable) per
include-self 3-of-4 cell, dumps the engine reasoning text for each,
and emits a deterministic markdown report ready for hand-classification
of the TP-rationale pattern (LEXICAL_CAPTURE / PROCESS_NARRATIVE_MISAPPLY
/ CONSTRUCT_CORRECT / ACCIDENTAL_OVERLAP / INSUFFICIENT_DATA).

Reproducible: zero API calls. Reads engine outputs from
fvs_eval/v4/grok_intra_rater_runs.json, panel labels from
fvs_eval/mixed_genre_{v1,v2}/labels/{family}_new_library_v{3,4}.json.

Output: fvs_eval/v4/tp_rationale_pattern_audit.md
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "fvs_eval" / "v4" / "grok_intra_rater_runs.json"
OUT = REPO / "fvs_eval" / "v4" / "tp_rationale_pattern_audit.md"

PANEL = ["claude_haiku_4_5", "gemini_3_1_flash_lite", "grok_4_1_fast", "gpt_5_4_mini"]
DETECTOR_FAMILY = "grok_4_1_fast"
DEFAULT_MODE = ["FVS-001", "FVS-002", "FVS-007", "FVS-008", "FVS-009",
                "FVS-011", "FVS-012", "FVS-014", "FVS-015"]

CORPUS_CFG = {
    "mg_v1": {
        "labels_dir": REPO / "fvs_eval" / "mixed_genre_v1" / "labels",
        "label_suffix": "new_library_v3",
        "engine_prefix": "mixed_genre_v1/",
    },
    "mg_v2": {
        "labels_dir": REPO / "fvs_eval" / "mixed_genre_v2" / "labels",
        "label_suffix": "new_library_v4",
        "engine_prefix": "mixed_genre_v2/",
    },
}


def fam_get(fam_labels, fam, doc, fid):
    cell = fam_labels[fam]["labels"][doc].get(fid)
    if cell is None:
        return None
    if isinstance(cell, bool):
        return cell
    if isinstance(cell, dict):
        return bool(cell.get("exhibits", False))
    return None


def load_engine(runs):
    out = {}
    for k, payload in runs.items():
        if "/" not in k:
            continue
        out[k] = {}
        for run_name in ("run_a", "run_b"):
            entries = payload.get(run_name, {}).get("entries", [])
            out[k][run_name] = {
                e["fvs_id"]: {
                    "exhibits": bool(e["exhibits"]),
                    "reasoning": e.get("reasoning", ""),
                }
                for e in entries
            }
    return out


def classify_per_doc_per_cell(corpus_id, cfg, engine):
    fam_labels = {}
    for fam in PANEL:
        p = cfg["labels_dir"] / f"{fam}_{cfg['label_suffix']}.json"
        fam_labels[fam] = json.loads(p.read_text())

    keys = sorted(k for k in engine if k.startswith(cfg["engine_prefix"]))
    doc_ids = sorted(k.split("/", 1)[1] for k in keys)

    out = {}
    for fid in DEFAULT_MODE:
        out[fid] = {"tp_docs": {}, "fp_docs": {}, "fn_docs": {}, "tn_docs": {}}
        for doc in doc_ids:
            full_key = f"{cfg['engine_prefix']}{doc}"
            votes = {fam: fam_get(fam_labels, fam, doc, fid) for fam in PANEL}
            if any(v is None for v in votes.values()):
                continue
            consensus = sum(votes.values()) >= 3
            ra = engine[full_key]["run_a"].get(fid, {})
            rb = engine[full_key]["run_b"].get(fid, {})
            ra_ex = ra.get("exhibits")
            rb_ex = rb.get("exhibits")
            if ra_ex is None or rb_ex is None:
                continue
            stable = ra_ex == rb_ex
            classification_runs = []
            for run_name, ex, rsn in (("run_a", ra_ex, ra.get("reasoning", "")),
                                       ("run_b", rb_ex, rb.get("reasoning", ""))):
                if ex and consensus:
                    bucket = "tp_docs"
                elif ex and not consensus:
                    bucket = "fp_docs"
                elif not ex and consensus:
                    bucket = "fn_docs"
                else:
                    bucket = "tn_docs"
                rec = out[fid][bucket].setdefault(doc, {
                    "panel_votes": {fam: bool(v) for fam, v in votes.items()},
                    "consensus": consensus,
                    "stable_across_runs": stable,
                    "rationales": {},
                })
                rec["rationales"][run_name] = {"exhibits": bool(ex), "reasoning": rsn}
                classification_runs.append(bucket)
    return out


def main():
    runs = json.loads(RUNS.read_text())
    engine = load_engine(runs)

    lines = []
    lines.append("# Per-frame TP/FP/FN rationale audit (all 9 default-mode frames)\n")
    lines.append("Auto-generated by `scripts/audit_tp_rationale_patterns.py`. Sources: `fvs_eval/v4/grok_intra_rater_runs.json` (engine outputs) + `fvs_eval/mixed_genre_{v1,v2}/labels/*_new_library_v{3,4}.json` (4-family panel labels). Consensus rule: 3-of-4 majority (include-self).\n")
    lines.append("Each frame section enumerates TP, FP, FN docs (run-pair stable + run-pair-flipping shown together; per-run classification appears in the rationales). TN docs are summarized in count only (subsample available on request).\n")
    lines.append("Classification surface for hand-coding (after reading rationales):\n")
    lines.append("- **LEXICAL_CAPTURE**: TP rationales cite the same construct word(s) the FP rationales cite; no construct-correct distinguisher between TPs and FPs.")
    lines.append("- **PROCESS_NARRATIVE_MISAPPLY**: TP rationales apply the construct's process narrative to static text in a way that produces accidental TPs.")
    lines.append("- **CONSTRUCT_CORRECT**: TP rationales cite distinguishing criteria that align with the library Identification's intended construct, separating them from FPs.")
    lines.append("- **ACCIDENTAL_OVERLAP**: TP rationales cite a non-construct criterion that happens to overlap with the construct in narrow cases.")
    lines.append("- **INSUFFICIENT_DATA**: TP count too low across both corpora for pattern recognition (n<2).")
    lines.append("")

    summary = {}
    for fid in DEFAULT_MODE:
        lines.append(f"\n## {fid}\n")
        per_corpus = {}
        for cid, cfg in CORPUS_CFG.items():
            per_corpus[cid] = classify_per_doc_per_cell(cid, cfg, engine)[fid]

        summary[fid] = {
            cid: {bucket: len(per_corpus[cid][bucket]) for bucket in ("tp_docs", "fp_docs", "fn_docs", "tn_docs")}
            for cid in CORPUS_CFG
        }

        lines.append(f"### {fid} cell counts\n")
        lines.append("| corpus | n_TP | n_FP | n_FN | n_TN |")
        lines.append("|---|---:|---:|---:|---:|")
        for cid in CORPUS_CFG:
            s = summary[fid][cid]
            lines.append(f"| {cid} | {s['tp_docs']} | {s['fp_docs']} | {s['fn_docs']} | {s['tn_docs']} |")

        for cid in CORPUS_CFG:
            data = per_corpus[cid]
            for bucket_name, bucket_label in (
                ("tp_docs", "True positives"),
                ("fp_docs", "False positives"),
                ("fn_docs", "False negatives"),
            ):
                docs = data[bucket_name]
                if not docs:
                    continue
                lines.append(f"\n#### {fid} {cid} {bucket_label} (n={len(docs)})\n")
                lines.append("| doc | stable? | run_a exhibits | run_a reasoning | run_b exhibits | run_b reasoning | panel votes |")
                lines.append("|---|---|---|---|---|---|---|")
                for doc, rec in sorted(docs.items()):
                    stable = "yes" if rec["stable_across_runs"] else "FLIPPED"
                    ra = rec["rationales"].get("run_a", {})
                    rb = rec["rationales"].get("run_b", {})
                    ra_r = ra.get("reasoning", "").replace("|", "\\|").replace("\n", " ")[:280]
                    rb_r = rb.get("reasoning", "").replace("|", "\\|").replace("\n", " ")[:280]
                    votes_str = ", ".join(f"{fam.split('_')[0]}={'T' if v else 'F'}" for fam, v in rec["panel_votes"].items())
                    lines.append(f"| {doc} | {stable} | {ra.get('exhibits','?')} | {ra_r} | {rb.get('exhibits','?')} | {rb_r} | {votes_str} |")

    lines.append("\n\n## Cross-frame TP/FP/FN summary\n")
    lines.append("| frame | mg_v1 TP | mg_v1 FP | mg_v1 FN | mg_v2 TP | mg_v2 FP | mg_v2 FN |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for fid in DEFAULT_MODE:
        s1 = summary[fid]["mg_v1"]
        s2 = summary[fid]["mg_v2"]
        lines.append(f"| {fid} | {s1['tp_docs']} | {s1['fp_docs']} | {s1['fn_docs']} | {s2['tp_docs']} | {s2['fp_docs']} | {s2['fn_docs']} |")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")
    print()
    print("Per-frame counts (mg_v1 + mg_v2 combined):")
    for fid in DEFAULT_MODE:
        s1 = summary[fid]["mg_v1"]
        s2 = summary[fid]["mg_v2"]
        print(f"  {fid}: TP={s1['tp_docs']+s2['tp_docs']} FP={s1['fp_docs']+s2['fp_docs']} FN={s1['fn_docs']+s2['fn_docs']}")


if __name__ == "__main__":
    main()
