"""Extract V4.2 engine reasoning text for FVS-007 false positives and
FVS-001 false negatives across mg_v1 + mg_v2, both runs. Reads the
diagnostic doc list and the engine runs file; writes a deterministic
markdown table.

Reproducible: zero API calls.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DIAG = REPO / "fvs_eval" / "v4" / "per_frame_007_001_diagnostic.json"
RUNS = REPO / "fvs_eval" / "v4" / "grok_intra_rater_runs.json"
OUT = REPO / "fvs_eval" / "v4" / "per_frame_007_001_rationales.md"

CORPUS_PREFIX = {"mg_v1": "mixed_genre_v1/", "mg_v2": "mixed_genre_v2/"}


def load_engine_reasoning(runs):
    out = {}
    for k, payload in runs.items():
        if "/" not in k:
            continue
        out[k] = {}
        for run_name in ("run_a", "run_b"):
            entries = payload.get(run_name, {}).get("entries", [])
            out[k][run_name] = {
                e["fvs_id"]: {
                    "exhibits": bool(e["exhibits"]),
                    "reasoning": e.get("reasoning", ""),
                }
                for e in entries
            }
    return out


def main():
    diag = json.loads(DIAG.read_text())
    runs = json.loads(RUNS.read_text())
    reasoning = load_engine_reasoning(runs)

    lines = []
    lines.append("# FVS-007 + FVS-001 V4.2 engine rationale extraction\n")
    lines.append("Auto-generated by `scripts/extract_fvs_007_001_rationales.py`. Sources: diagnostic JSON + engine intra-rater runs JSON.\n")

    for fid, error_class in (("FVS-007", "false_positives"), ("FVS-001", "false_negatives")):
        lines.append(f"\n## {fid} {error_class}\n")
        for cid, prefix in CORPUS_PREFIX.items():
            lines.append(f"\n### {cid} {fid} {error_class}\n")
            corpus = diag["by_corpus"][cid]
            union_key = "fp_doc_union" if error_class == "false_positives" else "fn_doc_union"
            doc_to_cells = corpus[union_key][fid]
            if not doc_to_cells:
                lines.append("(none)\n")
                continue
            lines.append("| doc | run_a exhibits | run_a reasoning | run_b exhibits | run_b reasoning | cells |")
            lines.append("|---|---|---|---|---|---|")
            for doc, cells in doc_to_cells.items():
                full_key = f"{prefix}{doc}"
                rec = reasoning.get(full_key, {})
                ra = rec.get("run_a", {}).get(fid, {})
                rb = rec.get("run_b", {}).get(fid, {})
                ra_ex = ra.get("exhibits", "?")
                rb_ex = rb.get("exhibits", "?")
                ra_r = ra.get("reasoning", "").replace("|", "\\|").replace("\n", " ")[:300]
                rb_r = rb.get("reasoning", "").replace("|", "\\|").replace("\n", " ")[:300]
                cell_str = ", ".join(c.replace("__", "/") for c in cells)
                lines.append(f"| {doc} | {ra_ex} | {ra_r} | {rb_ex} | {rb_r} | {cell_str} |")
            lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
